
        trigger:
        - main

        pool:
          vmImage: 'ubuntu-16.04' # set to windows-latest or another Windows vmImage for Windows builds

        variables:
          imageName: 'pipelines-javascript-docker'
          DockerImageName: 'azure-pipeline-project/clouddemo'
        steps:

        
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: app/Dockerfile
        - task: prisma-cloud-compute-scan@3
          inputs:
            scanType: 'images'
            twistlockService: 'Prisma-compute-credentials'
            artifact: $(imageName)
        - task: Docker@2
          displayName: 'Login to Container Registry'
          inputs:
            command: login
            containerRegistry: 'gcrServiceConnection'
        - task: Docker@2
          displayName: Push image
          inputs:
            containerRegistry: 'gcrServiceConnection'
            repository: $(imageName)
            command: push
            tags:
                test1
                test2