
        trigger:
        - main

        pool:
          vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

        variables:
          imageName: 'pipelines-javascript-docker'
          DockerImageName: 'azure-pipeline-project/clouddemo'
        steps:
        - task: prisma-cloud-compute-scan@3
          inputs:
            scanType: 'images'
            twistlockService: 'Prisma-compute-credentials'
            artifact: 'pipelines-javascript-docker'
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: app/Dockerfile
        - task: Docker@2
          displayName: 'Login to Container Registry'
          inputs:
            command: login
            containerRegistry: 'gcrServiceConnection'
        - task: Docker@2
          displayName: 'Build and push image'
          inputs:
            Dockerfile: 'app/Dockerfile'
            command: buildAndPush
            repository: '$(DockerImageName)'